version: '3.8'
services:
  transcription:
    build: ../services/transcription
    volumes:
      - ../data:/data
    depends_on:
      - api
  api:
    build: ../services/api
    volumes:
      - ../data:/data
    ports:
      - "8000:8000"
  web:
    build: ../services/web
    ports:
      - "3000:3000"
    depends_on:
      - api
